"""reconcile_schema

Revision ID: 754ed4cfa449
Revises: 001
Create Date: 2026-09-12 02:55:34.238133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "754ed4cfa449"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analytics_rules",
        "rule_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "zone_entry",
            "zone_exit",
            "dwell_time",
            "line_crossing",
            "occupancy_threshold",
            "class_presence",
            name="ruletype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_rules",
        "severity",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("low", "medium", "high", "critical", name="severity", native_enum=False),
        existing_nullable=False,
        existing_server_default=sa.text("'medium'::character varying"),
    )
    op.alter_column(
        "analytics_rules",
        "object_classes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "analytics_rules",
        "configuration",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column(
        "camera_sessions", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    )
    op.add_column(
        "camera_sessions", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    )
    op.alter_column(
        "camera_sessions", "status", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "camera_sessions",
        "error_message",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "cameras", "description", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.alter_column(
        "cameras",
        "source_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("local_video", "webcam", "rtsp", name="sourcetype", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "cameras", "source_uri", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
    )
    op.alter_column(
        "cameras",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "offline",
            "connecting",
            "online",
            "degraded",
            "error",
            "stopped",
            name="camerastatus",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'offline'::character varying"),
    )
    op.alter_column(
        "cameras",
        "status_message",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "cameras",
        "fps",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.add_column("events", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.alter_column(
        "events",
        "event_type",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "severity",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("low", "medium", "high", "critical", name="severity", native_enum=False),
        existing_nullable=False,
        existing_server_default=sa.text("'medium'::character varying"),
    )
    op.alter_column(
        "events",
        "object_class",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "active", "acknowledged", "resolved", "dismissed", name="eventstatus", native_enum=False
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.alter_column(
        "events",
        "fingerprint",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.add_column("evidence", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.alter_column(
        "evidence",
        "evidence_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("snapshot", "clip", name="evidencetype", native_enum=False),
        existing_nullable=False,
        existing_server_default=sa.text("'snapshot'::character varying"),
    )
    op.alter_column(
        "evidence",
        "file_path",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "mime_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=128),
        existing_nullable=False,
        existing_server_default=sa.text("'image/jpeg'::character varying"),
    )
    op.alter_column(
        "evidence",
        "metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column(
        "model_artifacts", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    )
    op.alter_column(
        "model_artifacts",
        "task",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "framework",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "weights_path",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "format",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "classes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "metrics",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column(
        "track_summaries", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    )
    op.add_column(
        "track_summaries", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    )
    op.alter_column(
        "track_summaries",
        "object_class",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "track_summaries",
        "zones_visited",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "track_summaries",
        "lines_crossed",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "track_summaries",
        "metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.alter_column(
        "virtual_lines",
        "start_point",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_lines",
        "end_point",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_lines",
        "direction_mode",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("both", "a_to_b", "b_to_a", name="directionmode", native_enum=False),
        existing_nullable=False,
        existing_server_default=sa.text("'both'::character varying"),
    )
    op.alter_column(
        "virtual_lines",
        "color",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=7),
        existing_nullable=False,
        existing_server_default=sa.text("'#EF4444'::character varying"),
    )
    op.alter_column(
        "zones",
        "zone_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "restricted",
            "entrance",
            "exit",
            "parking",
            "pedestrian",
            "loading",
            "custom",
            name="zonetype",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'custom'::character varying"),
    )
    op.alter_column(
        "zones",
        "points",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "zones",
        "color",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=7),
        existing_nullable=False,
        existing_server_default=sa.text("'#3B82F6'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "zones",
        "color",
        existing_type=sa.String(length=7),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'#3B82F6'::character varying"),
    )
    op.alter_column(
        "zones",
        "points",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "zones",
        "zone_type",
        existing_type=sa.Enum(
            "restricted",
            "entrance",
            "exit",
            "parking",
            "pedestrian",
            "loading",
            "custom",
            name="zonetype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'custom'::character varying"),
    )
    op.alter_column(
        "virtual_lines",
        "color",
        existing_type=sa.String(length=7),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'#EF4444'::character varying"),
    )
    op.alter_column(
        "virtual_lines",
        "direction_mode",
        existing_type=sa.Enum("both", "a_to_b", "b_to_a", name="directionmode", native_enum=False),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'both'::character varying"),
    )
    op.alter_column(
        "virtual_lines",
        "end_point",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_lines",
        "start_point",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "track_summaries",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "track_summaries",
        "lines_crossed",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "track_summaries",
        "zones_visited",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "track_summaries",
        "object_class",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("track_summaries", "updated_at")
    op.drop_column("track_summaries", "created_at")
    op.alter_column(
        "model_artifacts",
        "metrics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "model_artifacts",
        "classes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "model_artifacts",
        "format",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "weights_path",
        existing_type=sa.String(length=1024),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "framework",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "model_artifacts",
        "task",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("model_artifacts", "updated_at")
    op.alter_column(
        "evidence",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "evidence",
        "mime_type",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'image/jpeg'::character varying"),
    )
    op.alter_column(
        "evidence",
        "file_path",
        existing_type=sa.String(length=1024),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "evidence",
        "evidence_type",
        existing_type=sa.Enum("snapshot", "clip", name="evidencetype", native_enum=False),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'snapshot'::character varying"),
    )
    op.drop_column("evidence", "updated_at")
    op.alter_column(
        "events",
        "fingerprint",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "events",
        "status",
        existing_type=sa.Enum(
            "active", "acknowledged", "resolved", "dismissed", name="eventstatus", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.alter_column(
        "events",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "object_class",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "severity",
        existing_type=sa.Enum(
            "low", "medium", "high", "critical", name="severity", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'medium'::character varying"),
    )
    op.alter_column(
        "events",
        "event_type",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("events", "updated_at")
    op.alter_column(
        "cameras",
        "fps",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "cameras",
        "status_message",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "cameras",
        "status",
        existing_type=sa.Enum(
            "offline",
            "connecting",
            "online",
            "degraded",
            "error",
            "stopped",
            name="camerastatus",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'offline'::character varying"),
    )
    op.alter_column(
        "cameras", "source_uri", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "cameras",
        "source_type",
        existing_type=sa.Enum(
            "local_video", "webcam", "rtsp", name="sourcetype", native_enum=False
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "cameras", "description", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "camera_sessions",
        "error_message",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column("camera_sessions", "status", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.drop_column("camera_sessions", "updated_at")
    op.drop_column("camera_sessions", "created_at")
    op.alter_column(
        "analytics_rules",
        "configuration",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "analytics_rules",
        "object_classes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "analytics_rules",
        "severity",
        existing_type=sa.Enum(
            "low", "medium", "high", "critical", name="severity", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'medium'::character varying"),
    )
    op.alter_column(
        "analytics_rules",
        "rule_type",
        existing_type=sa.Enum(
            "zone_entry",
            "zone_exit",
            "dwell_time",
            "line_crossing",
            "occupancy_threshold",
            "class_presence",
            name="ruletype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
